sw9332/team_Cheese

- Assets/Player/PlayerAnimation/Player.controller
- Assets/Scenes/GameScene.unity
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/UI/DialogueManager.cs
대화창 넘기기 :
키보드 Z -> 다음 버튼 (클릭)
대화중 플레이어 이동 불가능
> Dialogue Fix

- Assets/Scenes/GameScene.unity
- Assets/Script/GameScene/Camera/MiniGame.cs
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/UI/DialogueManager.cs
대화창 출력 버그 수정
Z키를 사용하여 넘기기 가능
대사 출력 중, 넘기기 불가능 (스킵 불가능)
미니게임 없이 다음 스테이지로 넘어가던 버그 수정
> Dialogue Fix & MiniGame Fix

- Assets/Scenes/GameScene.unity
- Assets/Script/GameScene/Camera/MiniGame.cs
- Assets/Script/GameScene/Object/Table.cs
- Assets/Script/GameScene/Object/TeddyBearChair.cs
- Assets/Script/GameScene/Object/TeddyBearChair.cs.meta
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/UI/UIManager.cs
조건을 달성해야 미니게임을 플레이 가능하게 수정.
조건 1. 케잌을 테이블에 올려둘 것.
조건 2. 우측상단 의자에 곰인형을 올려둘 것.
조건 3. 테이블 앞에 플레이어가 서 있을 것.
미니게임 패스 조건 수정 (화면상으로 조금 더 자연스러워 보이도록 위치 조정
곰인형을 의자에 올리도록 유도하는 대사 추가.
> MiniGame Fix

- Assets/Scenes/MainScene.unity
- 설정UI 마우스 스크롤 속도 증가
- 해상도 설정 마우스 스크롤 속도 증가
> Update 2024.9.21 - 3

- Assets/Scenes/GameScene.unity
- ProjectSettings/TagManager.asset
> Update 2024.9.21 - 4

- Assets/Script/GameScene/Player/Inventory.cs
- GetItemObject if문 -> switch문
- GetItemSprite if문 -> switch문
> Inventory 코드 개선 - 2

- Assets/Scenes/GameScene.unity
- Assets/Script/GameScene/Player/Inventory.cs
- 아이템 줍기 코드 통합
- OnTriggerStay2D 줍기 if문 -> switch문
> Inventory 코드 개선 - 3

- Assets/Script/GameScene/Player/Inventory.cs
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/Player/PlayerControl.cs
- Assets/Script/GameScene/UI/DialogueManager.cs
- Assets/Script/GameScene/UI/Stamina.cs
- Player pos, PlayerControl isPush, isMove변수 static 제거.
- Player 맵 이동 코드 if문 -> switch문 변경.
- PlayerControl 불필요한 velocity변수 제거.
> 메모리 관리 최적화 업데이트 - 1

- Assets/Script/GameScene/Player/PlayerControl.cs
- Player 이동 방향 변경 시 애니메이션 겹치는 현상 수정.
> PlayerControl 코드 수정

- Assets/Script/GameScene/Camera/CameraManager.cs
- Assets/Script/GameScene/Player/Player.cs
- Player 불필요한 코드 제거.,
- CameraManager pos변수 static 제거.
> 메모리 관리 최적화 업데이트 - 2

- Assets/Script/GameScene/GameManager.cs
- GameManager 페이드 후 씬이 넘어가는 메서드 매개변수 추가.
> 메모리 관리 최적화 업데이트 - 3

- Assets/Scenes/GameScene.unity
- Assets/Scenes/MainScene.unity
- Assets/Script/GameScene/Camera/MiniGame.cs
- Assets/Script/GameScene/GameManager.cs
- Assets/Script/GameScene/UI/FadeManager.cs
- Assets/Script/GameScene/UI/FadeManager.cs.meta
- Assets/Script/GameScene/UI/Prologue.cs
- Assets/Script/GameScene/UI/UIManager.cs
- Assets/Script/MainScene/MainSceneManager.cs
- FadeManager 스크립트 추가
- Fade는 FadeManager에서 관리
> FadeManager 추가

- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/Player/PlayerControl.cs
플레이어의 hp가 자동적으로 배열에 추가되서 추가, 삭제 되도록
> getplayerHP Auto

- Assets/Object Prefab/item Prefab/bullet-export.png.meta
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/Player/PlayerControl.cs
- Assets/UI/albumImage/cakeImage.jpg.meta
- Assets/UI/camera_UI/Camara_UI.png.meta
- hp함수 Player->PlayerControl로 변경
기타 public변수들 private으로 변경
> playerHP관련 변경

- Assets/Object Prefab/item Prefab/bullet-export.png.meta
- Assets/Scenes/MainScene.unity
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/Player/PlayerControl.cs
- Assets/UI/albumImage/cakeImage.jpg.meta
- Assets/UI/camera_UI/Camara_UI.png.meta
- hp함수 Player->PlayerControl로 변경
기타 public변수들 private으로 변경
> playerHP관련 변경 

- Assets/Script/GameScene/Player/PlayerControl.cs
- Assets/Script/MainScene/MainSceneManager.cs
> 메모리 관리 최적화 업데이트 - 5

- Assets/Object Prefab/item Prefab/NPC.prefab
- Assets/Scenes/GameScene.unity
> NPC Prefab 수정

- Assets/Scenes/GameScene.unity
> Inventory NPC Sprite

- Assets/Object Prefab/Object Prefab/Right Chair.prefab
- Assets/Script/GameScene/Object/Object.cs
- Assets/Script/GameScene/Player/Inventory.cs
- Assets/Script/GameScene/Player/Player.cs
- Assets/Script/GameScene/Player/PlayerControl.cs
- Player가 Object에 충돌 했는지 확인 하는 변수 자료형 bool값으로 변경.
> Player Object 충돌

- Assets/Script/MainScene/GameSetting.cs
- 그래픽 설정 체크 Update -> 옵션 버튼 클릭시 설정.
> 그래픽 설정 최적화

- Assets/Script/MainScene/GameSetting.cs
> GameSetting

- Assets/DialogueEventManager.cs
- Assets/DialogueEventManager.cs.meta
- Assets/Scenes/GameScene.unity
- Assets/Script/Camera/MiniGame.cs
- Assets/Script/Player/Inventory.cs
- Assets/Script/Player/Player.cs
- DialogueEventManager에서 대화 이벤트 관리.
- Player pos변수 삭제.
> DialogueEventManager 추가

- Assets/Scenes/GameScene.unity
- Assets/Script/Manager/FadeManager.cs
- Assets/Script/Manager/TeleportManager.cs
> fadeManager

- Assets/Scenes/GameScene.unity
- Assets/Script/Camera/CameraManager.cs
- Assets/Script/Dialogue/DialogueManager.cs
- Assets/Script/Manager/FadeManager.cs
- Fade중에 대화창으로 인해 isMove가 켜지는 것과, 대화창이 실행 중일 때 FadeIn으로 인해 isMove가 켜지지 않도록 변경
> FadeManager, DialogueManager

- Assets/Script/Player/PlayerAttack.cs
> 이름 변경에 의한 오류 fix

- Assets/Scenes/GameScene.unity
- Assets/Script/Dialogue/DialogueContentManager.cs
- Assets/Script/Item/TeddyBearItem.cs
- Assets/Script/Object/Table.cs
- Assets/Script/Player/Inventory.cs
> Table Item

- Assets/Scenes/GameScene.unity
> Cake Event Animation

- Assets/Animation/PlayerAnimation/Player.controller
- Assets/Loot/Item Prefab/Ammo.prefab
- Assets/Loot/Item Prefab/ChocoBar.prefab
- Assets/Loot/Item Prefab/LootPrefab.prefab
- Assets/Resources/Sprite/Item Sprite/Brown Teddy Bear Sprite.png.meta
- Assets/Resources/Sprite/Item Sprite/Pink Teddy Bear Sprite.png.meta
- Assets/Resources/Sprite/Item Sprite/Yellow Teddy Bear Sprite.png.meta
- Assets/Scenes/GameScene.unity
- Assets/Script/Bullet/LootBag.cs
- Assets/Script/Enemy/Enemy.cs
- Assets/Script/Item/Item Object/LootItemPickUp.cs
- Assets/Script/Item/Item Object/LootItemPickUp.cs.meta
- Assets/Script/Manager/InventoryManager.cs
- Assets/Script/Player/PlayerControl.cs
- ProjectSettings/TagManager.asset
item drop 기능을 새로운 manager들에 추가
LootItemPickUp.cs는 loot item의 pick up 기능을 적용
> item drop function
